use serde_json::Value;

/// Generate an AGENTS.md file compatible with Cursor, Copilot, Codex, and Gemini.
pub fn generate(manifest: &Value) -> String {
    let mut out = String::with_capacity(4096);

    let name = str_or(manifest, &["identity", "name"], "project");
    let desc = str_or(manifest, &["identity", "description"], "");
    let lang = str_or(manifest, &["stack", "language"], "unknown");
    let fw = str_or(manifest, &["stack", "framework"], "none");
    let arch_type = str_or(manifest, &["archetype", "type"], "application");

    // Header
    out.push_str(&format!("# AGENTS.md — {name}\n\n"));
    if !desc.is_empty() {
        out.push_str(&format!("{desc}\n\n"));
    }

    // Stack
    let stack_label = if fw != "none" {
        format!("{lang} / {fw}")
    } else {
        lang.clone()
    };
    out.push_str(&format!("## Stack\n\n- **Language**: {lang}\n"));
    if fw != "none" {
        out.push_str(&format!("- **Framework**: {fw}\n"));
    }
    out.push_str(&format!("- **Archetype**: {arch_type}\n\n"));

    // Commands
    out.push_str("## Commands\n\n");
    for (label, key) in [
        ("Lint", "lint"),
        ("Test", "test"),
        ("Build", "build"),
        ("Install", "install"),
    ] {
        let cmd = str_or(manifest, &["commands", key], "NOT_CONFIGURED");
        if cmd != "NOT_CONFIGURED" {
            out.push_str(&format!("- **{label}**: `{cmd}`\n"));
        }
    }
    out.push('\n');

    // Key files
    if let Some(source_dirs) = manifest["structure"]["source_dirs"].as_array() {
        if !source_dirs.is_empty() {
            out.push_str("## Key Files\n\n");
            for dir in source_dirs {
                if let Some(d) = dir.as_str() {
                    out.push_str(&format!("- `{d}/` — source code\n"));
                }
            }
            if let Some(test_dirs) = manifest["structure"]["test_dirs"].as_array() {
                for dir in test_dirs {
                    if let Some(d) = dir.as_str() {
                        out.push_str(&format!("- `{d}/` — tests\n"));
                    }
                }
            }
            if let Some(entries) = manifest["structure"]["entry_points"].as_array() {
                for e in entries.iter().take(5) {
                    if let Some(s) = e.as_str() {
                        out.push_str(&format!("- `{s}` — entry point\n"));
                    }
                }
            }
            out.push('\n');
        }
    }

    // Conventions
    out.push_str("## Conventions\n\n");
    out.push_str(&conventions_for(&lang, &arch_type));

    // Footer
    out.push_str(&format!(
        "\n---\n\n*Generated by aiframework v2. Stack: {stack_label}.*\n"
    ));

    out
}

/// Return conventions based on language and archetype.
fn conventions_for(lang: &str, archetype: &str) -> String {
    let mut rules = Vec::new();

    match lang.to_lowercase().as_str() {
        "rust" => {
            rules.push("- Follow Rust 2021 edition idioms");
            rules.push("- Use `Result` for fallible operations, avoid `unwrap()` in library code");
            rules.push("- Run `cargo clippy` before committing");
        }
        "python" => {
            rules.push("- Follow PEP 8 style guidelines");
            rules.push("- Use type hints for all public functions");
            rules.push("- Prefer f-strings over format()");
        }
        "javascript" | "typescript" => {
            rules.push("- Use strict mode / strict TypeScript config");
            rules.push("- Prefer const over let; avoid var");
            rules.push("- Handle async errors with try/catch");
        }
        "go" => {
            rules.push("- Run `go vet` and `golint` before committing");
            rules.push("- Handle all errors explicitly; no blank `_` for errors");
            rules.push("- Follow standard Go project layout");
        }
        "ruby" => {
            rules.push("- Follow Ruby community style guide");
            rules.push("- Prefer symbols over strings for hash keys");
        }
        "java" | "kotlin" => {
            rules.push("- Follow standard Java naming conventions");
            rules.push("- Use dependency injection where appropriate");
        }
        _ => {
            rules.push("- Follow established project conventions");
        }
    }

    match archetype {
        "cli-tool" => rules.push("- All commands must have --help with usage examples"),
        "web-app" | "api" => rules.push("- All endpoints must validate input"),
        "library" => rules.push("- All public APIs must be documented"),
        _ => {}
    }

    rules.push("- Write tests for new functionality");
    rules.push("- Keep commits atomic and well-described");

    let mut out = String::new();
    for r in rules {
        out.push_str(r);
        out.push('\n');
    }
    out
}

/// Navigate nested JSON safely.
fn str_or(value: &Value, path: &[&str], default: &str) -> String {
    let mut current = value;
    for key in path {
        current = &current[*key];
    }
    current.as_str().unwrap_or(default).to_string()
}
