use serde_json::Value;

/// Generate a .github/workflows/ci.yml from the project manifest.
pub fn generate(manifest: &Value) -> String {
    let lang = str_or(manifest, &["stack", "language"], "unknown");
    let lint_cmd = str_or(manifest, &["commands", "lint"], "");
    let test_cmd = str_or(manifest, &["commands", "test"], "");
    let build_cmd = str_or(manifest, &["commands", "build"], "");
    let install_cmd = str_or(manifest, &["commands", "install"], "");

    let mut out = String::with_capacity(2048);

    out.push_str("# Auto-generated by aiframework — CI workflow\n");
    out.push_str("name: CI\n\n");
    out.push_str("on:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\n");
    out.push_str("jobs:\n  ci:\n    runs-on: ubuntu-latest\n    steps:\n");
    out.push_str("      - uses: actions/checkout@v4\n\n");

    // Language-specific setup
    out.push_str(&setup_step(&lang, manifest));

    // Install dependencies
    if !install_cmd.is_empty() {
        out.push_str(&format!(
            "      - name: Install dependencies\n        run: {install_cmd}\n\n"
        ));
    }

    // Lint step
    if !lint_cmd.is_empty() {
        out.push_str(&format!(
            "      - name: Lint\n        run: {lint_cmd}\n\n"
        ));
    }

    // Test step
    if !test_cmd.is_empty() {
        out.push_str(&format!(
            "      - name: Test\n        run: {test_cmd}\n\n"
        ));
    }

    // Build step
    if !build_cmd.is_empty() {
        out.push_str(&format!(
            "      - name: Build\n        run: {build_cmd}\n"
        ));
    }

    out
}

/// Return the appropriate setup step for a given language.
fn setup_step(lang: &str, manifest: &Value) -> String {
    match lang.to_lowercase().as_str() {
        "javascript" | "typescript" => {
            let version = str_or(manifest, &["stack", "language_version"], "20");
            let pkg_mgr = str_or(manifest, &["stack", "package_manager"], "npm");
            let cache = match pkg_mgr.as_str() {
                "yarn" => "yarn",
                "pnpm" => "pnpm",
                _ => "npm",
            };
            format!(
                "      - uses: actions/setup-node@v4\n        with:\n          node-version: \"{version}\"\n          cache: \"{cache}\"\n\n"
            )
        }
        "python" => {
            let version = str_or(manifest, &["stack", "language_version"], "3.12");
            format!(
                "      - uses: actions/setup-python@v5\n        with:\n          python-version: \"{version}\"\n\n"
            )
        }
        "rust" => {
            "      - uses: dtolnay/rust-toolchain@stable\n\n".to_string()
        }
        "go" => {
            let version = str_or(manifest, &["stack", "language_version"], "1.22");
            format!(
                "      - uses: actions/setup-go@v5\n        with:\n          go-version: \"{version}\"\n\n"
            )
        }
        "ruby" => {
            let version = str_or(manifest, &["stack", "language_version"], "3.3");
            format!(
                "      - uses: ruby/setup-ruby@v1\n        with:\n          ruby-version: \"{version}\"\n          bundler-cache: true\n\n"
            )
        }
        "java" | "kotlin" => {
            let version = str_or(manifest, &["stack", "language_version"], "21");
            format!(
                "      - uses: actions/setup-java@v4\n        with:\n          distribution: temurin\n          java-version: \"{version}\"\n\n"
            )
        }
        _ => String::new(),
    }
}

/// Navigate nested JSON safely, returning empty string for NOT_CONFIGURED.
fn str_or(value: &Value, path: &[&str], default: &str) -> String {
    let mut current = value;
    for key in path {
        current = &current[*key];
    }
    match current.as_str() {
        Some(s) if s != "NOT_CONFIGURED" => s.to_string(),
        _ => default.to_string(),
    }
}
