use serde_json::Value;

/// Generate docs/reference/architecture.md from manifest + code index.
/// Returns a Markdown string with module overview, file structure, top files, and language breakdown.
pub fn generate(manifest: &Value, code_index: Option<&Value>) -> String {
    let mut out = String::with_capacity(4096);

    let name = str_or(manifest, &["identity", "name"], "Project");
    let lang = str_or(manifest, &["stack", "language"], "unknown");
    let fw = str_or(manifest, &["stack", "framework"], "none");
    let arch_type = str_or(manifest, &["archetype", "type"], "application");
    let arch_complexity = str_or(manifest, &["archetype", "complexity"], "moderate");

    let stack_label = if fw != "none" {
        format!("{lang}/{fw}")
    } else {
        lang.clone()
    };

    // Header
    out.push_str(&format!("# {name} — Architecture Reference\n\n"));
    out.push_str(&format!(
        "> Auto-generated by aiframework. Stack: {stack_label} | Archetype: {arch_type} | Complexity: {arch_complexity}\n\n"
    ));

    // Module overview from code index
    if let Some(index) = code_index {
        if let Some(modules) = index["_meta"]["modules"].as_array() {
            if !modules.is_empty() {
                out.push_str("## Module Overview\n\n");
                out.push_str("| Module | Files | Description |\n");
                out.push_str("|--------|-------|-------------|\n");
                for m in modules.iter().take(30) {
                    let mod_name = m["name"].as_str().unwrap_or("unknown");
                    let file_count = m["file_count"].as_u64().unwrap_or(0);
                    out.push_str(&format!("| `{mod_name}` | {file_count} | - |\n"));
                }
                out.push('\n');
            }
        }
    }

    // File structure tree from source/test dirs
    out.push_str("## Directory Structure\n\n```\n");
    if let Some(source_dirs) = manifest["structure"]["source_dirs"].as_array() {
        for dir in source_dirs {
            if let Some(d) = dir.as_str() {
                out.push_str(&format!("{d}/          # Source code\n"));
            }
        }
    }
    if let Some(test_dirs) = manifest["structure"]["test_dirs"].as_array() {
        for dir in test_dirs {
            if let Some(d) = dir.as_str() {
                out.push_str(&format!("{d}/          # Tests\n"));
            }
        }
    }
    if let Some(config_files) = manifest["structure"]["config_files"].as_array() {
        for f in config_files.iter().take(10) {
            if let Some(s) = f.as_str() {
                out.push_str(&format!("{s}\n"));
            }
        }
    }
    out.push_str("```\n\n");

    // Top files by PageRank
    if let Some(index) = code_index {
        if let Some(top_files) = index["_meta"]["top_files"].as_array() {
            if !top_files.is_empty() {
                out.push_str("## Key Files (by dependency rank)\n\n");
                out.push_str("| File | Importance |\n");
                out.push_str("|------|------------|\n");
                for entry in top_files.iter().take(20) {
                    let file = entry["file"].as_str().unwrap_or("?");
                    let score = entry["importance"].as_u64().unwrap_or(0);
                    if score > 0 {
                        out.push_str(&format!("| `{file}` | {score} |\n"));
                    }
                }
                out.push('\n');
            }
        }

        // Language breakdown
        if let Some(langs) = index["_meta"]["languages"].as_object() {
            if !langs.is_empty() {
                out.push_str("## Language Breakdown\n\n");
                out.push_str("| Language | Files |\n");
                out.push_str("|----------|-------|\n");
                for (lang_name, count) in langs {
                    let n = count.as_u64().unwrap_or(0);
                    out.push_str(&format!("| {lang_name} | {n} |\n"));
                }
                out.push('\n');
            }
        }
    }

    // Entry points
    if let Some(entries) = manifest["structure"]["entry_points"].as_array() {
        if !entries.is_empty() {
            out.push_str("## Entry Points\n\n");
            for e in entries.iter().take(10) {
                if let Some(s) = e.as_str() {
                    out.push_str(&format!("- `{s}`\n"));
                }
            }
            out.push('\n');
        }
    }

    // Footer
    out.push_str("---\n\n*Generated by aiframework. Do not edit manually — re-run `aiframework refresh` to update.*\n");

    out
}

/// Navigate nested JSON safely.
fn str_or(value: &Value, path: &[&str], default: &str) -> String {
    let mut current = value;
    for key in path {
        current = &current[*key];
    }
    current.as_str().unwrap_or(default).to_string()
}
