use serde_json::Value;
use std::path::Path;

/// Generate .githooks/pre-commit and .githooks/pre-push scripts.
/// Returns the list of files created relative to target.
pub fn generate(
    target: &Path,
    manifest: &Value,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut created = Vec::new();

    let lint_cmd = str_or(manifest, &["commands", "lint"], "");
    let test_cmd = str_or(manifest, &["commands", "test"], "");

    // Nothing to generate if no commands configured
    if lint_cmd.is_empty() && test_cmd.is_empty() {
        return Ok(created);
    }

    let hooks_dir = target.join(".githooks");
    std::fs::create_dir_all(&hooks_dir)?;

    // pre-commit: run lint
    if !lint_cmd.is_empty() {
        let pre_commit = generate_pre_commit(&lint_cmd);
        let path = hooks_dir.join("pre-commit");
        std::fs::write(&path, &pre_commit)?;
        make_executable(&path)?;
        created.push(".githooks/pre-commit".into());
    }

    // pre-push: run lint + test
    {
        let pre_push = generate_pre_push(&lint_cmd, &test_cmd);
        let path = hooks_dir.join("pre-push");
        std::fs::write(&path, &pre_push)?;
        make_executable(&path)?;
        created.push(".githooks/pre-push".into());
    }

    Ok(created)
}

fn generate_pre_commit(lint_cmd: &str) -> String {
    let mut out = String::with_capacity(512);
    out.push_str("#!/usr/bin/env bash\n");
    out.push_str("set -euo pipefail\n\n");
    out.push_str("# Auto-generated by aiframework — pre-commit hook\n");
    out.push_str("# Runs lint before each commit.\n\n");
    out.push_str("echo \"[pre-commit] Running lint...\"\n");
    out.push_str(&format!("{lint_cmd}\n"));
    out.push_str("echo \"[pre-commit] Lint passed.\"\n");
    out
}

fn generate_pre_push(lint_cmd: &str, test_cmd: &str) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str("#!/usr/bin/env bash\n");
    out.push_str("set -euo pipefail\n\n");
    out.push_str("# Auto-generated by aiframework — pre-push hook\n");
    out.push_str("# Runs lint + test before each push.\n\n");

    if !lint_cmd.is_empty() {
        out.push_str("echo \"[pre-push] Running lint...\"\n");
        out.push_str(&format!("{lint_cmd}\n\n"));
    }

    if !test_cmd.is_empty() {
        out.push_str("echo \"[pre-push] Running tests...\"\n");
        out.push_str(&format!("{test_cmd}\n\n"));
    }

    out.push_str("echo \"[pre-push] All checks passed.\"\n");
    out
}

/// Set the executable bit on a file (Unix only).
#[cfg(unix)]
fn make_executable(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = std::fs::metadata(path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms)?;
    Ok(())
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    // No-op on non-Unix platforms
    Ok(())
}

/// Navigate nested JSON safely.
fn str_or(value: &Value, path: &[&str], default: &str) -> String {
    let mut current = value;
    for key in path {
        current = &current[*key];
    }
    match current.as_str() {
        Some(s) if s != "NOT_CONFIGURED" => s.to_string(),
        _ => default.to_string(),
    }
}
