use serde_json::Value;
use std::path::Path;

/// Generate .githooks/pre-commit and .githooks/pre-push scripts.
/// Returns the list of files created relative to target.
pub fn generate(
    target: &Path,
    manifest: &Value,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut created = Vec::new();

    let lint_cmd = str_or(manifest, &["commands", "lint"], "");
    let test_cmd = str_or(manifest, &["commands", "test"], "");

    // Nothing to generate if no commands configured
    if lint_cmd.is_empty() && test_cmd.is_empty() {
        return Ok(created);
    }

    let hooks_dir = target.join(".githooks");
    std::fs::create_dir_all(&hooks_dir)?;

    // pre-commit: run lint
    if !lint_cmd.is_empty() {
        let pre_commit = generate_pre_commit(&lint_cmd);
        let path = hooks_dir.join("pre-commit");
        std::fs::write(&path, &pre_commit)?;
        make_executable(&path)?;
        created.push(".githooks/pre-commit".into());
    }

    // pre-push: run lint + test
    {
        let pre_push = generate_pre_push(&lint_cmd, &test_cmd);
        let path = hooks_dir.join("pre-push");
        std::fs::write(&path, &pre_push)?;
        make_executable(&path)?;
        created.push(".githooks/pre-push".into());
    }

    Ok(created)
}

fn generate_pre_commit(lint_cmd: &str) -> String {
    let mut out = String::with_capacity(512);
    out.push_str("#!/usr/bin/env bash\n");
    out.push_str("set -euo pipefail\n\n");
    out.push_str("# Auto-generated by aiframework — pre-commit hook\n");
    out.push_str("# Runs lint before each commit.\n\n");
    out.push_str("echo \"[pre-commit] Running lint...\"\n");
    out.push_str(&format!("{lint_cmd}\n"));
    out.push_str("echo \"[pre-commit] Lint passed.\"\n");
    out
}

fn generate_pre_push(lint_cmd: &str, test_cmd: &str) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str("#!/usr/bin/env bash\n");
    out.push_str("set -euo pipefail\n\n");
    out.push_str("# Auto-generated by aiframework — pre-push hook\n");
    out.push_str("# Self-contained: runs lint + test before each push.\n");
    out.push_str("# No external sources or bash libraries required.\n\n");
    out.push_str("failures=0\n\n");

    if !lint_cmd.is_empty() {
        out.push_str("echo \"[pre-push] Running lint...\"\n");
        out.push_str(&format!("if ! {lint_cmd}; then\n"));
        out.push_str("  echo \"[pre-push] FAIL: lint failed\" >&2\n");
        out.push_str("  failures=$((failures + 1))\n");
        out.push_str("fi\n\n");
    }

    if !test_cmd.is_empty() {
        out.push_str("echo \"[pre-push] Running tests...\"\n");
        out.push_str(&format!("if ! {test_cmd}; then\n"));
        out.push_str("  echo \"[pre-push] FAIL: tests failed\" >&2\n");
        out.push_str("  failures=$((failures + 1))\n");
        out.push_str("fi\n\n");
    }

    out.push_str("if [ \"$failures\" -ne 0 ]; then\n");
    out.push_str("  echo \"[pre-push] $failures check(s) failed — push blocked.\" >&2\n");
    out.push_str("  exit 1\n");
    out.push_str("fi\n\n");
    out.push_str("echo \"[pre-push] All checks passed.\"\n");
    out
}

/// Set the executable bit on a file (Unix only).
#[cfg(unix)]
fn make_executable(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = std::fs::metadata(path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(path, perms)?;
    Ok(())
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    // No-op on non-Unix platforms
    Ok(())
}

/// Generate `.claude/settings.json` with PostToolUse auto-format hooks,
/// PreToolUse safety guards, and permission auto-allow rules.
///
/// Reads the formatter from `manifest["quality"]["formatter"]["tool"]` and maps
/// it to the appropriate CLI command. Skips generation if the file already exists.
pub fn generate_claude_settings(
    target: &Path,
    manifest: &Value,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let settings_path = target.join(".claude/settings.json");
    if settings_path.exists() {
        return Ok(Vec::new());
    }

    let claude_dir = target.join(".claude");
    std::fs::create_dir_all(&claude_dir)?;

    let formatter_tool = str_or(manifest, &["quality", "formatter", "tool"], "");
    let format_cmd = formatter_command(&formatter_tool);

    let settings = build_claude_settings(&format_cmd);
    std::fs::write(&settings_path, &settings)?;

    Ok(vec![".claude/settings.json".into()])
}

/// Map a detected formatter tool name to the CLI command that formats a single file.
fn formatter_command(tool: &str) -> String {
    let normalized = tool.to_lowercase();
    if normalized.contains("prettier") {
        "npx prettier --write \"$CLAUDE_TOOL_INPUT_FILE\" 2>/dev/null || true".into()
    } else if normalized.contains("ruff") {
        "ruff format \"$CLAUDE_TOOL_INPUT_FILE\" 2>/dev/null || true".into()
    } else if normalized.contains("rustfmt") {
        "rustfmt \"$CLAUDE_TOOL_INPUT_FILE\" 2>/dev/null || true".into()
    } else if normalized.contains("gofmt") || normalized.contains("goimports") {
        "gofmt -w \"$CLAUDE_TOOL_INPUT_FILE\" 2>/dev/null || true".into()
    } else if normalized.contains("black") {
        "black \"$CLAUDE_TOOL_INPUT_FILE\" 2>/dev/null || true".into()
    } else {
        String::new()
    }
}

/// Build the full `.claude/settings.json` content as a formatted JSON string.
fn build_claude_settings(format_cmd: &str) -> String {
    let mut hooks = Vec::<String>::new();

    // ── SessionStart hook ──────────────────────────────────────────────
    hooks.push(r#"    {
      "matcher": "SessionStart",
      "hooks": [
        {
          "type": "command",
          "command": "bash .claude/hooks/session-start.sh"
        }
      ]
    }"#.into());

    // ── PostToolUse: auto-format after Write|Edit ──────────────────────
    if !format_cmd.is_empty() {
        hooks.push(format!(
            r#"    {{
      "matcher": "Write|Edit",
      "hooks": [
        {{
          "type": "command",
          "command": "bash -c '{format_cmd}'"
        }}
      ]
    }}"#
        ));
    }

    // ── Stop hook: learning reminder ───────────────────────────────────
    hooks.push(r#"    {
      "matcher": "Stop",
      "hooks": [
        {
          "type": "command",
          "command": "bash -c 'echo \"Reminder: run /sheal-retro to extract session learnings.\"'"
        }
      ]
    }"#.into());

    // ── PreToolUse: block dangerous Bash commands ──────────────────────
    hooks.push(r#"    {
      "matcher": "Bash",
      "hooks": [
        {
          "type": "command",
          "command": "bash -c 'CMD=\"$CLAUDE_TOOL_INPUT\"; if echo \"$CMD\" | grep -qE \"rm -rf /|DROP TABLE|git push.*--force.*main|git reset --hard\"; then echo \"{\\\"decision\\\": \\\"block\\\", \\\"reason\\\": \\\"Dangerous command detected. Review manually.\\\"}\"; fi'"
        }
      ]
    }"#.into());

    // ── PreToolUse: block production config edits ──────────────────────
    hooks.push(r#"    {
      "matcher": "Write|Edit",
      "hooks": [
        {
          "type": "command",
          "command": "bash -c 'FILE=\"$CLAUDE_TOOL_INPUT_FILE\"; if echo \"$FILE\" | grep -qE \"\\.env\\.prod|\\.env\\.production|production\\.yml|prod\\.conf\"; then echo \"{\\\"decision\\\": \\\"block\\\", \\\"reason\\\": \\\"Production config file. Edit staging config instead.\\\"}\"; fi'"
        }
      ]
    }"#.into());

    // ── PermissionRequest: auto-allow safe commands ────────────────────
    hooks.push(r#"    {
      "matcher": "Bash",
      "hooks": [
        {
          "type": "command",
          "command": "bash -c 'CMD=\"$CLAUDE_TOOL_INPUT\"; if echo \"$CMD\" | grep -qE \"^(npm test|npm run lint|npx prettier|cargo test|cargo clippy|make test|make lint|go test|pytest|ruff)\"; then echo \"{\\\"decision\\\": \\\"allow\\\"}\"; fi'"
        }
      ]
    }"#.into());

    let hooks_json = hooks.join(",\n");

    format!(
        r#"{{
  "permissions": {{
    "allow": [
      "Read",
      "Glob",
      "Grep",
      "WebSearch"
    ]
  }},
  "hooks": [
{hooks_json}
  ]
}}
"#
    )
}

/// Navigate nested JSON safely.
fn str_or(value: &Value, path: &[&str], default: &str) -> String {
    let mut current = value;
    for key in path {
        current = &current[*key];
    }
    match current.as_str() {
        Some(s) if s != "NOT_CONFIGURED" => s.to_string(),
        _ => default.to_string(),
    }
}
