pub mod agents_md;
pub mod ci;
pub mod claude_md;
pub mod cursorrules;
pub mod docs;
pub mod hooks;
pub mod rules;
pub mod skills;
pub mod tracking;
pub mod vault;

use serde_json::Value;
use std::path::Path;

/// Generate all output files from a manifest + code index.
/// Skips files that already exist to avoid overwriting user customizations.
pub fn generate(
    target: &Path,
    manifest: &Value,
    code_index: Option<&Value>,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut generated = Vec::new();

    // CLAUDE.md — always write (it's the primary output)
    let claude_md = claude_md::generate(manifest, code_index);
    let claude_path = target.join("CLAUDE.md");
    write_if_missing_or_generated(&claude_path, &claude_md)?;
    generated.push("CLAUDE.md".into());

    // AGENTS.md — multi-agent config (Cursor, Copilot, Codex, Gemini)
    let agents_path = target.join("AGENTS.md");
    if !agents_path.exists() {
        let agents_md = agents_md::generate(manifest);
        std::fs::write(&agents_path, &agents_md)?;
        generated.push("AGENTS.md".into());
    }

    // .cursorrules — Cursor IDE configuration
    let cursorrules_path = target.join(".cursorrules");
    if !cursorrules_path.exists() {
        let cursorrules_content = cursorrules::generate(manifest);
        std::fs::write(&cursorrules_path, &cursorrules_content)?;
        generated.push(".cursorrules".into());
    }

    // .githooks/pre-commit + pre-push (skip if hooks already exist)
    let hooks_dir = target.join(".githooks");
    if !hooks_dir.join("pre-commit").exists() {
        let hook_files = hooks::generate(target, manifest)?;
        generated.extend(hook_files);
    }

    // .github/workflows/ci.yml (skip if CI already configured)
    let ci_path = target.join(".github/workflows/ci.yml");
    if !ci_path.exists() {
        let ci_content = ci::generate(manifest);
        let ci_dir = target.join(".github/workflows");
        std::fs::create_dir_all(&ci_dir)?;
        std::fs::write(&ci_path, &ci_content)?;
        generated.push(".github/workflows/ci.yml".into());
    }

    // docs/reference/architecture.md
    let arch_path = target.join("docs/reference/architecture.md");
    if !arch_path.exists() {
        let docs_dir = target.join("docs/reference");
        std::fs::create_dir_all(&docs_dir)?;
        let docs_content = docs::generate(manifest, code_index);
        std::fs::write(&arch_path, &docs_content)?;
        generated.push("docs/reference/architecture.md".into());
    }

    // .claude/skills/{short}-review and {short}-ship
    let skill_files = skills::generate(target, manifest)?;
    generated.extend(skill_files);

    // .claude/rules/workflow.md
    let rule_files = rules::generate(target, manifest)?;
    generated.extend(rule_files);

    // vault/ directory structure
    let vault_files = vault::generate(target, manifest, code_index)?;
    generated.extend(vault_files);

    // tools/learnings/{short}-learnings.jsonl
    let tracking_files = tracking::generate(target, manifest)?;
    generated.extend(tracking_files);

    Ok(generated)
}

/// Write file if it doesn't exist or was generated by aiframework (has our footer).
fn write_if_missing_or_generated(
    path: &Path,
    content: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if path.exists() {
        // Only overwrite if the file was generated by us
        let existing = std::fs::read_to_string(path)?;
        if existing.contains("Generated by aiframework") {
            std::fs::write(path, content)?;
        }
        // Otherwise skip — user owns this file
    } else {
        std::fs::write(path, content)?;
    }
    Ok(())
}
