use serde_json::Value;
use std::path::Path;

/// Generate .claude/rules/workflow.md with auto-loaded workflow rules.
/// Returns the list of files created relative to target.
pub fn generate(
    target: &Path,
    manifest: &Value,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut created = Vec::new();

    let rules_dir = target.join(".claude/rules");
    let workflow_path = rules_dir.join("workflow.md");

    if workflow_path.exists() {
        return Ok(created);
    }

    std::fs::create_dir_all(&rules_dir)?;

    let lint = str_or(manifest, &["commands", "lint"], "");
    let typecheck = str_or(manifest, &["commands", "typecheck"], "");
    let test_cmd = str_or(manifest, &["commands", "test"], "");

    let mut out = String::with_capacity(4096);

    out.push_str("# Workflow Rules\n\n");

    // Plan vs Execute
    out.push_str("## Plan vs Execute\n\n");
    out.push_str("- Enter plan mode for ANY non-trivial task (3+ steps or architectural decisions)\n");
    out.push_str("- If something goes sideways, STOP and re-plan — don't keep pushing\n");
    out.push_str("- When given a task with clear scope: start executing immediately\n");
    out.push_str("- When hitting a wall (3+ failed attempts), stop and re-plan approach\n\n");

    // Verification
    out.push_str("## Verification Before Done\n\n");
    out.push_str("Never mark a task complete without proving it works.\n\n");
    out.push_str("```bash\n");
    if !lint.is_empty() {
        out.push_str(&format!("# Lint\n{lint}\n\n"));
    }
    if !typecheck.is_empty() {
        out.push_str(&format!("# Type check\n{typecheck}\n\n"));
    }
    if !test_cmd.is_empty() {
        out.push_str(&format!("# Test\n{test_cmd}\n\n"));
    }
    out.push_str("```\n\n");
    out.push_str("All verification commands must pass before marking done.\n\n");

    // Git safety
    out.push_str("## Git Safety\n\n");
    out.push_str("- After fixes: `git add` + `git commit` — do NOT push until user says so\n");
    out.push_str("- NEVER push to main without explicit user confirmation\n");
    out.push_str("- NEVER commit secrets, API keys, or credentials\n");
    out.push_str("- Batch related changes into logical commits\n\n");

    // Autonomous iteration
    out.push_str("## Autonomous Iteration\n\n");
    out.push_str("- Execute fix, verify with tests, if broken fix again, loop until clean\n");
    out.push_str("- Iterate autonomously on fixable issues — don't ask for hand-holding\n");
    out.push_str("- Commit after each logical group of verified fixes\n\n");

    // QA auto-fix
    out.push_str("## QA Auto-Fix\n\n");
    out.push_str("When tests discover issues, fix them automatically:\n\n");
    out.push_str("1. Run tests — collect all failures\n");
    out.push_str("2. Fix each failure: identify root cause, fix implementation (never skip a test)\n");
    out.push_str("3. Run tests again — all must pass\n");
    out.push_str("4. If fix-verify loop fails 3+ times on same issue, STOP and re-plan\n\n");

    // Documentation
    out.push_str("## Documentation Sync\n\n");
    out.push_str("After ANY feature, refactor, or significant change, update:\n\n");
    out.push_str("- CLAUDE.md — if change adds invariants, new key locations, or commands\n");
    out.push_str("- docs/ — update relevant documentation files\n");
    out.push_str("- CHANGELOG.md + VERSION — for user-facing changes\n\n");

    // Footer
    out.push_str("---\n\n*Generated by aiframework. Customize freely — this file won't be overwritten.*\n");

    std::fs::write(&workflow_path, &out)?;
    created.push(".claude/rules/workflow.md".into());

    Ok(created)
}

/// Navigate nested JSON safely, filtering out NOT_CONFIGURED.
fn str_or(value: &Value, path: &[&str], default: &str) -> String {
    let mut current = value;
    for key in path {
        current = &current[*key];
    }
    match current.as_str() {
        Some(s) if s != "NOT_CONFIGURED" => s.to_string(),
        _ => default.to_string(),
    }
}
