use serde_json::Value;
use std::path::Path;

/// Generate vault/ directory structure with status.md, decisions dir, and wiki index.
/// Returns the list of files created relative to target.
pub fn generate(
    target: &Path,
    manifest: &Value,
    code_index: Option<&Value>,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut created = Vec::new();

    let vault_root = target.join("vault");

    // Skip if vault already initialized
    if vault_root.join(".initialized").exists() {
        return Ok(created);
    }

    let name = str_or(manifest, &["identity", "name"], "Project");
    let lang = str_or(manifest, &["stack", "language"], "unknown");
    let fw = str_or(manifest, &["stack", "framework"], "none");

    let stack_label = if fw != "none" {
        format!("{lang}/{fw}")
    } else {
        lang.clone()
    };

    // Create directory structure
    std::fs::create_dir_all(vault_root.join("memory/decisions"))?;
    std::fs::create_dir_all(vault_root.join("wiki"))?;
    created.push("vault/memory/decisions/".into());

    // vault/memory/status.md
    let status_path = vault_root.join("memory/status.md");
    if !status_path.exists() {
        let status = format!(
            "# {name} — Session Status\n\n\
             > Stack: {stack_label}\n\n\
             ## Current State\n\n\
             - **Last updated**: (not yet)\n\
             - **Active work**: none\n\
             - **Blocked on**: nothing\n\n\
             ## Recent Decisions\n\n\
             (none yet — decisions logged in `vault/memory/decisions/`)\n\n\
             ## Notes\n\n\
             Update this file at the end of each session.\n\n\
             ---\n\n\
             *Generated by aiframework.*\n"
        );
        std::fs::write(&status_path, &status)?;
        created.push("vault/memory/status.md".into());
    }

    // vault/wiki/index.md
    let index_path = vault_root.join("wiki/index.md");
    if !index_path.exists() {
        let mut index = String::with_capacity(2048);
        index.push_str(&format!("# {name} — Wiki Index\n\n"));
        index.push_str(&format!("> Knowledge base for {name} ({stack_label})\n\n"));
        index.push_str("## Source Files\n\n");

        // List source files from code index
        if let Some(ci) = code_index {
            if let Some(files) = ci["files"].as_array() {
                for entry in files.iter().take(50) {
                    if let Some(path) = entry["path"].as_str() {
                        index.push_str(&format!("- `{path}`\n"));
                    }
                }
            } else if let Some(top_files) = ci["_meta"]["top_files"].as_array() {
                for entry in top_files.iter().take(30) {
                    if let Some(file) = entry["file"].as_str() {
                        index.push_str(&format!("- `{file}`\n"));
                    }
                }
            }
        }

        // Fallback: list source dirs
        if let Some(source_dirs) = manifest["structure"]["source_dirs"].as_array() {
            if !source_dirs.is_empty() {
                index.push_str("\n## Source Directories\n\n");
                for dir in source_dirs {
                    if let Some(d) = dir.as_str() {
                        index.push_str(&format!("- `{d}/`\n"));
                    }
                }
            }
        }

        index.push_str("\n---\n\n*Generated by aiframework. Update as the project evolves.*\n");
        std::fs::write(&index_path, &index)?;
        created.push("vault/wiki/index.md".into());
    }

    // Write initialized marker
    std::fs::write(vault_root.join(".initialized"), "aiframework vault\n")?;

    Ok(created)
}

/// Navigate nested JSON safely.
fn str_or(value: &Value, path: &[&str], default: &str) -> String {
    let mut current = value;
    for key in path {
        current = &current[*key];
    }
    current.as_str().unwrap_or(default).to_string()
}
