use serde_json::Value;
use std::path::Path;

/// Ingest manifest data into vault wiki entity pages.
/// For each source file in the code index, creates vault/wiki/entities/{slug}.md.
pub fn generate(
    target: &Path,
    manifest: &Value,
    code_index: Option<&Value>,
) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut created = Vec::new();

    let code_index = match code_index {
        Some(ci) => ci,
        None => return Ok(created),
    };

    let entities_dir = target.join("vault/wiki/entities");

    // Skip if entities dir already has files (don't overwrite existing pages)
    if entities_dir.exists() {
        let has_files = std::fs::read_dir(&entities_dir)?
            .filter_map(|e| e.ok())
            .any(|e| e.path().extension().map(|x| x == "md").unwrap_or(false));
        if has_files {
            return Ok(created);
        }
    }

    let files = match code_index["files"].as_array() {
        Some(f) => f,
        None => return Ok(created),
    };

    if files.is_empty() {
        return Ok(created);
    }

    std::fs::create_dir_all(&entities_dir)?;

    let project_name = manifest["identity"]["name"]
        .as_str()
        .unwrap_or("Project");

    // Build an edge lookup: file -> imported_by list
    let mut imported_by: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();
    for entry in files {
        let source = entry["path"].as_str().unwrap_or("");
        if let Some(imports) = entry["imports"].as_array() {
            for imp in imports {
                if let Some(target_path) = imp.as_str() {
                    imported_by
                        .entry(target_path.to_string())
                        .or_default()
                        .push(source.to_string());
                }
            }
        }
    }

    // Limit to top 50 files by importance (PageRank score)
    let mut ranked: Vec<&Value> = files.iter().collect();
    ranked.sort_by(|a, b| {
        let sa = a["importance"].as_u64().unwrap_or(0);
        let sb = b["importance"].as_u64().unwrap_or(0);
        sb.cmp(&sa)
    });
    ranked.truncate(50);

    for entry in &ranked {
        let path = match entry["path"].as_str() {
            Some(p) => p,
            None => continue,
        };

        let slug = slugify(path);
        let lang = entry["language"].as_str().unwrap_or("unknown");
        let complexity = entry["complexity"].as_u64().unwrap_or(0);
        let importance = entry["importance"].as_u64().unwrap_or(0);

        let mut page = String::with_capacity(1024);
        page.push_str(&format!("# {path}\n\n"));
        page.push_str(&format!("> Part of {project_name}\n\n"));
        page.push_str(&format!("- **Language**: {lang}\n"));
        page.push_str(&format!("- **Complexity**: {complexity}\n"));
        page.push_str(&format!("- **Importance (PageRank)**: {importance}\n\n"));

        // Symbols
        if let Some(symbols) = entry["symbols"].as_array() {
            if !symbols.is_empty() {
                page.push_str("## Symbols\n\n");
                for sym in symbols {
                    let name = sym["name"].as_str().unwrap_or("?");
                    let kind = sym["kind"].as_str().unwrap_or("symbol");
                    page.push_str(&format!("- `{name}` ({kind})\n"));
                }
                page.push('\n');
            }
        }

        // Imports
        if let Some(imports) = entry["imports"].as_array() {
            if !imports.is_empty() {
                page.push_str("## Imports\n\n");
                for imp in imports {
                    if let Some(i) = imp.as_str() {
                        page.push_str(&format!("- `{i}`\n"));
                    }
                }
                page.push('\n');
            }
        }

        // Imported by
        if let Some(iby) = imported_by.get(path) {
            if !iby.is_empty() {
                page.push_str("## Imported By\n\n");
                for src in iby {
                    page.push_str(&format!("- `{src}`\n"));
                }
                page.push('\n');
            }
        }

        page.push_str("---\n\n*Generated by aiframework.*\n");

        let file_path = entities_dir.join(format!("{slug}.md"));
        std::fs::write(&file_path, &page)?;
        created.push(format!("vault/wiki/entities/{slug}.md"));
    }

    Ok(created)
}

/// Convert a file path to a URL-safe slug: replace / and . with -
fn slugify(path: &str) -> String {
    path.replace('/', "-").replace('.', "-")
}
