use serde_json::Value;

/// Generate vault/wiki/concepts/architecture.md — a graph overview page.
/// Shows module dependency graph, top files by PageRank, circular deps, and language breakdown.
pub fn generate(manifest: &Value, code_index: Option<&Value>) -> String {
    let project_name = manifest["identity"]["name"]
        .as_str()
        .unwrap_or("Project");

    let mut out = String::with_capacity(4096);
    out.push_str(&format!("# {project_name} — Architecture Graph\n\n"));
    out.push_str("> Auto-generated dependency overview\n\n");

    // Language breakdown
    if let Some(ci) = code_index {
        if let Some(langs) = ci["_meta"]["languages"].as_object() {
            out.push_str("## Language Breakdown\n\n");
            out.push_str("| Language | Files |\n");
            out.push_str("|----------|-------|\n");
            let mut lang_vec: Vec<(&String, &Value)> = langs.iter().collect();
            lang_vec.sort_by(|a, b| {
                let ca = b.1.as_u64().unwrap_or(0);
                let cb = a.1.as_u64().unwrap_or(0);
                ca.cmp(&cb)
            });
            for (lang, count) in &lang_vec {
                let n = count.as_u64().unwrap_or(0);
                out.push_str(&format!("| {lang} | {n} |\n"));
            }
            out.push('\n');
        }
    }

    // Top 10 files by PageRank
    if let Some(ci) = code_index {
        if let Some(top_files) = ci["_meta"]["top_files"].as_array() {
            out.push_str("## Top 10 Files by PageRank\n\n");
            out.push_str("```\n");
            out.push_str("  Score  File\n");
            out.push_str("  ─────  ────────────────────────────────────\n");
            for entry in top_files.iter().take(10) {
                let file = entry["file"].as_str().unwrap_or("?");
                let score = entry["importance"].as_u64().unwrap_or(0);
                out.push_str(&format!("  {score:>5}  {file}\n"));
            }
            out.push_str("```\n\n");
        }
    }

    // Module dependency graph (text diagram)
    if let Some(ci) = code_index {
        if let Some(modules) = ci["modules"].as_array() {
            if !modules.is_empty() {
                out.push_str("## Module Dependency Graph\n\n");
                out.push_str("```\n");
                for module in modules {
                    let name = module["name"].as_str().unwrap_or("?");
                    if let Some(deps) = module["depends_on"].as_array() {
                        if deps.is_empty() {
                            out.push_str(&format!("  {name}\n"));
                        } else {
                            for dep in deps {
                                let dep_name = dep.as_str().unwrap_or("?");
                                out.push_str(&format!("  {name} ──▶ {dep_name}\n"));
                            }
                        }
                    } else {
                        out.push_str(&format!("  {name}\n"));
                    }
                }
                out.push_str("```\n\n");
            }
        }
    }

    // Circular dependency warnings
    let mut has_circular = false;
    if let Some(ci) = code_index {
        if let Some(modules) = ci["modules"].as_array() {
            for module in modules {
                if let Some(circular) = module["circular_deps"].as_array() {
                    if !circular.is_empty() {
                        if !has_circular {
                            out.push_str("## Circular Dependencies ⚠\n\n");
                            has_circular = true;
                        }
                        let name = module["name"].as_str().unwrap_or("?");
                        for dep in circular {
                            let dep_name = dep.as_str().unwrap_or("?");
                            out.push_str(&format!(
                                "- **{name}** ↔ **{dep_name}** (circular)\n"
                            ));
                        }
                    }
                }
            }
        }
    }
    if has_circular {
        out.push('\n');
    }

    // Source directories from manifest
    if let Some(source_dirs) = manifest["structure"]["source_dirs"].as_array() {
        if !source_dirs.is_empty() {
            out.push_str("## Source Directories\n\n");
            for dir in source_dirs {
                if let Some(d) = dir.as_str() {
                    out.push_str(&format!("- `{d}/`\n"));
                }
            }
            out.push('\n');
        }
    }

    out.push_str("---\n\n*Generated by aiframework.*\n");
    out
}
