#!/bin/bash
# aiframework session-start hook for Claude Code
# Checks project health and returns suggestions via systemMessage.
# Generated by aiframework — customize as needed.
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
MSGS=""
add() { MSGS="${MSGS}${1}\n"; }

# Is repo bootstrapped?
[[ ! -f "$PROJECT_DIR/CLAUDE.md" ]] && add "Run: aiframework run --target . (generates CLAUDE.md and project config)"

# Is CLAUDE.md stale?
if [[ -f "$PROJECT_DIR/CLAUDE.md" && -f "$PROJECT_DIR/.aiframework/manifest.json" ]]; then
  if [[ "$(uname)" == "Darwin" ]]; then
    AGE=$(( ($(date +%s) - $(stat -f %m "$PROJECT_DIR/CLAUDE.md")) / 86400 ))
  else
    AGE=$(( ($(date +%s) - $(stat -c %Y "$PROJECT_DIR/CLAUDE.md")) / 86400 ))
  fi
  [[ "$AGE" -gt 14 ]] && add "CLAUDE.md is ${AGE} days old. Run: aiframework refresh"
fi

# Code index?
[[ -d "$PROJECT_DIR/.aiframework" && ! -f "$PROJECT_DIR/.aiframework/code-index.json" ]] && \
  add "No code index. Run: aiframework index --target ."

# Companion tools
command -v sheal &>/dev/null || add "Install sheal for session intelligence: npm install -g @liwala/sheal"
[[ -d "$HOME/.claude/skills/gstack" ]] || add "Install gstack for 37 workflow skills: git clone https://github.com/garrytan/gstack ~/.claude/skills/gstack"

# Output
if [[ -n "$MSGS" ]]; then
  printf '%s' "aiframework: $MSGS" | jq -Rs '{continue: true, systemMessage: .}'
fi
