#!/usr/bin/env bash
# Generator: AGENTS.md
# Produces a universal AGENTS.md following the AAIF spec.
# Read by Codex, Cursor, Copilot, Gemini, and other AI agents.

generate_agents_md() {
  local m="$MANIFEST"
  local out="$TARGET_DIR/AGENTS.md"

  if [[ "$DRY_RUN" == true ]]; then
    log_info "[DRY RUN] Would write AGENTS.md to $out"
    return 0
  fi

  # Preserve: skip if exists without aiframework marker
  if [[ -f "$out" ]] && ! grep -q 'Generated by aiframework' "$out" 2>/dev/null; then
    log_info "Preserved existing AGENTS.md (not generated by aiframework)"
    return 0
  fi

  local name desc lang fw short
  name=$(echo "$m" | jq -r '.identity.name')
  desc=$(echo "$m" | jq -r '.identity.description // "No description"')
  lang=$(echo "$m" | jq -r '.stack.language')
  fw=$(echo "$m" | jq -r '.stack.framework // "none"')
  short=$(echo "$m" | jq -r '.identity.short_name')

  local build_cmd test_cmd lint_cmd install_cmd typecheck format_cmd
  build_cmd=$(echo "$m" | jq -r '.commands.build // empty' | grep -v '^NOT_CONFIGURED$' || true)
  test_cmd=$(echo "$m" | jq -r '.commands.test // empty' | grep -v '^NOT_CONFIGURED$' || true)
  lint_cmd=$(echo "$m" | jq -r '.commands.lint // empty' | grep -v '^NOT_CONFIGURED$' || true)
  install_cmd=$(echo "$m" | jq -r '.commands.install // empty' | grep -v '^NOT_CONFIGURED$' || true)
  typecheck=$(echo "$m" | jq -r '.commands.typecheck // empty' | grep -v '^NOT_CONFIGURED$' || true)
  format_cmd=$(echo "$m" | jq -r '.commands.format // empty' | grep -v '^NOT_CONFIGURED$' || true)

  # Start writing
  # Clean description: skip HTML, NOT_FOUND, or empty
  local clean_desc="$desc"
  if [[ "$clean_desc" == "<"* || "$clean_desc" == "NOT_FOUND" || "$clean_desc" == "No description" || -z "$clean_desc" ]]; then
    clean_desc=""
  fi

  cat > "$out" << AGENTS_HEADER
# AGENTS.md — ${name}
$(if [[ -n "$clean_desc" ]]; then echo ""; echo "> ${clean_desc}"; fi)

**Stack:** ${lang} / ${fw}

AGENTS_HEADER

  # Build & Test section
  echo "## Build & Test" >> "$out"
  echo "" >> "$out"
  echo '```bash' >> "$out"
  [[ -n "$install_cmd" ]] && echo "# Install dependencies"$'\n'"${install_cmd}"$'\n' >> "$out"
  [[ -n "$build_cmd" ]] && echo "# Build"$'\n'"${build_cmd}"$'\n' >> "$out"
  [[ -n "$test_cmd" ]] && echo "# Test"$'\n'"${test_cmd}"$'\n' >> "$out"
  [[ -n "$lint_cmd" ]] && echo "# Lint"$'\n'"${lint_cmd}"$'\n' >> "$out"
  [[ -n "$typecheck" ]] && echo "# Type check"$'\n'"${typecheck}"$'\n' >> "$out"
  [[ -n "$format_cmd" ]] && echo "# Format"$'\n'"${format_cmd}"$'\n' >> "$out"

  # If nothing configured
  if [[ -z "$install_cmd" && -z "$build_cmd" && -z "$test_cmd" && -z "$lint_cmd" ]]; then
    echo "# No commands configured" >> "$out"
  fi
  echo '```' >> "$out"
  echo "" >> "$out"

  # Architecture section
  local arch_type arch_maturity complexity
  arch_type=$(echo "$m" | jq -r '.archetype.type // "unknown"')
  arch_maturity=$(echo "$m" | jq -r '.archetype.maturity // "unknown"')
  complexity=$(echo "$m" | jq -r '.archetype.complexity // "unknown"')

  echo "## Architecture" >> "$out"
  echo "" >> "$out"
  if [[ "$arch_type" != "unknown" ]]; then
    echo "- **Type:** ${arch_type} (${arch_maturity}, ${complexity})" >> "$out"
  fi

  # Entry points
  local entries
  entries=$(echo "$m" | jq -r '.structure.entry_points[]' 2>/dev/null)
  if [[ -n "$entries" ]]; then
    local entries_inline
    entries_inline=$(echo "$entries" | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')
    echo "- **Entry points:** ${entries_inline}" >> "$out"
  fi

  # Key directories
  local src_dirs
  src_dirs=$(echo "$m" | jq -r '.structure.directories[:5][]' 2>/dev/null)
  if [[ -n "$src_dirs" ]]; then
    echo "- **Key directories:** $(echo "$src_dirs" | tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')" >> "$out"
  fi
  echo "" >> "$out"

  # Code Style section — language-specific QA rules
  local qa_data_file="$ROOT_DIR/lib/data/languages.json"
  local qa_rules=""
  if [[ -f "$qa_data_file" ]] && command -v jq &>/dev/null; then
    qa_rules=$(jq -r --arg l "$lang" '.languages[$l].qa_rules[]? // empty' "$qa_data_file" 2>/dev/null)
  fi

  echo "## Code Style" >> "$out"
  echo "" >> "$out"
  if [[ -n "$qa_rules" ]]; then
    while IFS= read -r rule; do
      [[ -z "$rule" ]] && continue
      echo "- ${rule}" >> "$out"
    done <<< "$qa_rules"
  else
    echo "- Follow ${lang} community conventions and idioms" >> "$out"
    echo "- Code must pass all configured quality gates before merge" >> "$out"
  fi
  echo "" >> "$out"

  # Security section — from detected domains
  local domain_count
  domain_count=$(echo "$m" | jq '.domain.detected_domains | length' 2>/dev/null || echo "0")

  local has_auth has_api has_ai
  has_auth=$(echo "$m" | jq -r '.domain.detected_domains[] | select(.name == "auth") | .name' 2>/dev/null)
  has_api=$(echo "$m" | jq -r '.domain.detected_domains[] | select(.name == "api") | .name' 2>/dev/null)
  has_ai=$(echo "$m" | jq -r '.domain.detected_domains[] | select(.name == "ai") | .name' 2>/dev/null)

  echo "## Security" >> "$out"
  echo "" >> "$out"
  echo "- Never commit secrets, credentials, or API keys — use environment variables" >> "$out"
  [[ -n "$has_auth" ]] && echo "- All protected endpoints must have auth middleware" >> "$out"
  [[ -n "$has_api" ]] && echo "- Validate and sanitize all API inputs before processing" >> "$out"
  [[ -n "$has_ai" ]] && echo "- Never trust LLM output as safe — validate all AI-generated content" >> "$out"
  echo "" >> "$out"

  # Boundaries section — invariants
  echo "## Boundaries" >> "$out"
  echo "" >> "$out"

  if [[ "$domain_count" -gt 0 ]]; then
    echo "$m" | jq -r '.domain.detected_domains[] | .name' 2>/dev/null | while IFS= read -r domain; do
      case "$domain" in
        auth) echo "- Auth guards required on all protected endpoints" ;;
        database)
          local orm_val
          orm_val=$(echo "$m" | jq -r '.domain.detected_domains[] | select(.name == "database") | .orm // "ORM"')
          echo "- Database access through ${orm_val} only — no raw SQL" ;;
        api) echo "- Input validation on all API endpoints" ;;
        ai) echo "- LLM trust boundary — validate all AI output" ;;
        sandbox) echo "- Sandbox isolation for code execution" ;;
      esac
    done >> "$out"
  fi
  echo "- No secrets in source code" >> "$out"
  echo "" >> "$out"

  # Footer
  echo "---" >> "$out"
  echo "" >> "$out"
  echo "*Generated by aiframework. Run \`aiframework refresh\` to update.*" >> "$out"

  log_ok "AGENTS.md written to $out"
}
