#!/usr/bin/env bash
# Generator: .cursorrules
# Produces a .cursorrules file for Cursor IDE.
# Contains project commands, conventions, and invariants.

generate_cursor_rules() {
  local m="$MANIFEST"
  local out="$TARGET_DIR/.cursorrules"

  if [[ "$DRY_RUN" == true ]]; then
    log_info "[DRY RUN] Would write .cursorrules to $out"
    return 0
  fi

  # Preserve: skip if exists without aiframework marker
  if [[ -f "$out" ]] && ! grep -q 'Generated by aiframework' "$out" 2>/dev/null; then
    log_info "Preserved existing .cursorrules (not generated by aiframework)"
    return 0
  fi

  local name lang fw short
  name=$(echo "$m" | jq -r '.identity.name')
  lang=$(echo "$m" | jq -r '.stack.language')
  fw=$(echo "$m" | jq -r '.stack.framework // "none"')
  short=$(echo "$m" | jq -r '.identity.short_name')

  local build_cmd test_cmd lint_cmd typecheck format_cmd
  build_cmd=$(echo "$m" | jq -r '.commands.build // empty')
  test_cmd=$(echo "$m" | jq -r '.commands.test // empty')
  lint_cmd=$(echo "$m" | jq -r '.commands.lint // empty')
  typecheck=$(echo "$m" | jq -r '.commands.typecheck // empty')
  format_cmd=$(echo "$m" | jq -r '.commands.format // empty')

  cat > "$out" << CURSOR_HEADER
# .cursorrules — ${name}
# Stack: ${lang} / ${fw}
# Generated by aiframework. Run \`aiframework refresh\` to update.

CURSOR_HEADER

  # Commands
  echo "## Commands" >> "$out"
  echo "" >> "$out"
  [[ -n "$build_cmd" ]] && echo "- Build: \`${build_cmd}\`" >> "$out"
  [[ -n "$test_cmd" ]] && echo "- Test: \`${test_cmd}\`" >> "$out"
  [[ -n "$lint_cmd" ]] && echo "- Lint: \`${lint_cmd}\`" >> "$out"
  [[ -n "$typecheck" ]] && echo "- Type check: \`${typecheck}\`" >> "$out"
  [[ -n "$format_cmd" ]] && echo "- Format: \`${format_cmd}\`" >> "$out"
  echo "" >> "$out"

  # Conventions
  echo "## Conventions" >> "$out"
  echo "" >> "$out"

  # Language-specific QA rules
  local qa_data_file="$ROOT_DIR/lib/data/languages.json"
  local qa_rules=""
  if [[ -f "$qa_data_file" ]] && command -v jq &>/dev/null; then
    qa_rules=$(jq -r --arg l "$lang" '.languages[$l].qa_rules[]? // empty' "$qa_data_file" 2>/dev/null)
  fi

  if [[ -n "$qa_rules" ]]; then
    while IFS= read -r rule; do
      [[ -z "$rule" ]] && continue
      echo "- ${rule}" >> "$out"
    done <<< "$qa_rules"
  else
    echo "- Follow ${lang} community conventions" >> "$out"
  fi
  echo "- Never commit secrets or credentials — use environment variables" >> "$out"
  echo "- Run lint + test before committing" >> "$out"
  echo "" >> "$out"

  # Key locations
  echo "## Key Locations" >> "$out"
  echo "" >> "$out"
  local entries
  entries=$(echo "$m" | jq -r '.structure.entry_points[:5][]' 2>/dev/null)
  if [[ -n "$entries" ]]; then
    while IFS= read -r entry; do
      echo "- Entry: \`${entry}\`" >> "$out"
    done <<< "$entries"
  fi
  local src_dirs
  src_dirs=$(echo "$m" | jq -r '.structure.directories[:5][]' 2>/dev/null)
  if [[ -n "$src_dirs" ]]; then
    while IFS= read -r sdir; do
      echo "- Source: \`${sdir}/\`" >> "$out"
    done <<< "$src_dirs"
  fi
  echo "" >> "$out"

  log_ok ".cursorrules written to $out"
}
